#!/bin/bash

set -e

VERSION=v1.6.9

help() {
  echo "Usage:"
  echo "  zmicro package install curlie <args...>"
  echo ""
}

install() {
  local arch="$(os::arch)"
  local os="linux"
  local bin_path=/usr/bin

  if [ "$(os::is_macos)" = "true" ]; then
    os="darwin"
    bin_path=/usr/local/bin
  fi

  local tmp_file=/tmp/curlie.tar.gz

  local url="https://github.com/rs/curlie/releases/download/${VERSION}/curlie_${VERSION:1}_${os}_${arch}.tar.gz"
  curl -fSL $url -o $tmp_file

  cd /tmp
  tar -zxvf $tmp_file >>/dev/null 2>&1

  sudo mv curlie $bin_path

  rm -rf $tmp_file
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  install
  log::success "install curlie success."
}

run() {
  core $@
}

run $@
